---
title: "Report: How a series was detrended"
output: html_document
params:
  fileName: NA
  rwlObject: NA
  indivSeriesParam: NA
---

```{r,echo=TRUE, message=FALSE} 
library(tidyverse)
library(dplR)
library(gridExtra)
```

```{r,echo=FALSE, message=FALSE}
rwlObject <- params$rwlObject
indivSeriesParam <- params$indivSeriesParam
```


```{r,echo=FALSE}
if(is.null(params$fileName)){
  fname <- "DemoData.rwl"
}

if(!is.null(params$fileName)){
  fname <- params$fileName
}

```

### Date: `r Sys.Date()`

### File: `r fname`

### R Code

```
library(dplR)
dat <- read.rwl("`r fname`")

```


```{r,eval=FALSE,echo=FALSE}
dat <- rwlObject
nSeries <- ncol(dat)

for(i in 1:nSeries){
  mask <- is.na(dat[,i])
  seriesDF <- data.frame(y=dat[,i]) %>%
    drop_na() %>%
    mutate(x=1:length(y))
  
  res <- detrend.series(y = seriesDF$y,
                        method = indivSeriesParam$method[i],
                        nyrs = indivSeriesParam$nyrs2[i],
                        pos.slope = as.logical(indivSeriesParam$pos.slope[i]),
                        bass = indivSeriesParam$bass[i],
                        make.plot = FALSE,
                        verbose = FALSE,
                        return.info = TRUE,
                        difference = as.logical(indivSeriesParam$difference[i]))
  seriesDF$Curve <- res$curve
  seriesDF$Fits <- res$series
  
  pSeries <- ggplot(seriesDF) +
    geom_line(aes(x=x,y=y)) +
    scale_x_continuous(name = "Index",position = "top",expand=c(0,0)) +
    labs(y="Raw",title=paste0("Series: ",names(dat)[i]))
  
  if(indivSeriesParam$method[i] != "Ar"){
    pSeries <- pSeries + geom_line(aes(x=x,y=Curve),color="darkred",size=1)
  }
  
  pFits <- ggplot(seriesDF) +
    geom_hline(yintercept = as.integer(round(mean(seriesDF$Fits,na.rm=TRUE))),
               linetype="dashed") +
    geom_line(aes(x=x,y=Fits)) +
    scale_x_continuous(name = "Index",expand=c(0,0)) +
    labs(y="RWI")
  
  # make sure the axes are the same precision.
  pSeries <- pSeries +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01))
  
  pFits <- pFits +
    scale_y_continuous(labels = scales::number_format(accuracy = 0.01))
  
  pSeries <- pSeries + theme_minimal(base_size = 14) +
    theme(plot.background = element_rect(color = "grey70",size=0.5))
  pFits <- pFits + theme_minimal(base_size = 14) +
    theme(plot.background = element_rect(color = "grey70",size=0.5))
  
  pCombined <- grid.arrange(pSeries,pFits)
  pCombined
}
```

```{r,eval=FALSE}

res <- detrend.series(y = seriesDF$y,
                      method = method2use,
                      nyrs = nyrs2use,
                      pos.slope = pos.slope2use,
                      bass = bass2use,
                      make.plot = FALSE,
                      verbose = FALSE,
                      return.info = TRUE,
                      difference = difference2use)

pSeries <- ggplot(seriesDF) +
  geom_line(aes(x=x,y=y)) +
  scale_x_continuous(name = "Index",position = "top",expand=c(0,0)) +
  labs(y="Raw",title=paste0("Series: ",names(dat)[i]),
       subtitle = subTxt)

if(method2use != "Ar"){
  pSeries <- pSeries + geom_line(aes(x=x,y=Curve),color="darkred",size=1)
}

pFits <- ggplot(seriesDF) +
  geom_hline(yintercept = as.integer(round(mean(seriesDF$Fits,na.rm=TRUE))),
             linetype="dashed") +
  geom_line(aes(x=x,y=Fits)) +
  scale_x_continuous(name = "Index",expand=c(0,0)) +
  labs(y="RWI",caption = capTxt)

# make sure the axes are the same precision.
pSeries <- pSeries +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.01))

pFits <- pFits +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.01))

pSeries <- pSeries + theme_minimal(base_size = 14) +
  theme(plot.background = element_rect(color = "grey70",size=0.5))
pFits <- pFits + theme_minimal(base_size = 14) +
  theme(plot.background = element_rect(color = "grey70",size=0.5))

pCombined <- grid.arrange(pSeries,pFits)

return(pCombined)


```

