---
title: "Report: Individual Series Plots from iDetrend"
output: html_document
params:
  fileName: NA
  rwlObject: NA
  indivSeriesParam: NA
---

```{r,echo=FALSE, message=FALSE}
library(dplR)
```

```{r,echo=FALSE, message=FALSE}
rwlObject <- params$rwlObject
indivSeriesParam <- params$indivSeriesParam
```


```{r,echo=FALSE}
if(is.null(params$fileName)){
  fname <- "DemoData.rwl"
}

if(!is.null(params$fileName)){
  fname <- params$fileName
}

```

### Date: `r Sys.Date()`

### File: `r fname`

### Series Plots

```{r,eval=TRUE,echo=FALSE,message=FALSE,warning=FALSE,fig.width = 10, fig.height = 5}
dat <- rwlObject
nSeries <- ncol(dat)
for(i in 1:nSeries){
  cat("Series ",i, " of ", nSeries,"\n")
  mask <- is.na(dat[,i])
  seriesDF <- data.frame(y=dat[,i]) %>%
    drop_na() %>%
    mutate(x=1:length(y))

  res <- detrend.series(y = seriesDF$y,
                        method = indivSeriesParam$method[i],
                        nyrs = indivSeriesParam$nyrs2[i],
                        pos.slope = as.logical(indivSeriesParam$pos.slope[i]),
                        bass = indivSeriesParam$bass[i],
                        make.plot = FALSE,
                        verbose = FALSE,
                        return.info = TRUE,
                        difference = as.logical(indivSeriesParam$difference[i]))
  seriesDF$Curve <- res$curve
  seriesDF$Fits <- res$series

        if(res$dirtyDog){
          capTxt <- "ARSTAN would tell you this is a dirty dog"

          if(indivSeriesParam$method[i] == "Ar"){
            subTxt <- paste0("Warning: detrend method (",indivSeriesParam$method[i],
                             ") resulted in negative fits which were set to 0")
            if(as.logical(indivSeriesParam$difference[i]) == TRUE){
              subTxt <- paste0(subTxt, " before differencing")
            }
          }

          else {
            subTxt <- paste0("Warning: requested detrend method (",indivSeriesParam$method[i],
                             ") resulted in negative fits, detrended with: ",
                             res$model.info[[1]]$method)
          }
        }
        else {
          subTxt <- paste0("Detrend method: ",res$model.info[[1]]$method)
          capTxt <- ""
        }

        ### make the plot and return it
        pSeries <- ggplot(seriesDF) +
          geom_line(aes(x=x,y=y)) +
          scale_x_continuous(name = "Index",position = "top",expand=c(0,0)) +
          labs(y="Raw",title=paste0("Series: ",names(dat)[i]),
               subtitle = subTxt)

        if(indivSeriesParam$method[i] != "Ar"){
          pSeries <- pSeries + geom_line(aes(x=x,y=Curve),color="darkred",size=1)
        }

        pFits <- ggplot(seriesDF) +
          geom_hline(yintercept = as.integer(round(mean(seriesDF$Fits,na.rm=TRUE))),
                     linetype="dashed") +
          geom_line(aes(x=x,y=Fits)) +
          scale_x_continuous(name = "Index",expand=c(0,0)) +
          labs(y="RWI",caption = capTxt)

        # make sure the axes are the same precision.
        pSeries <- pSeries +
          scale_y_continuous(labels = scales::number_format(accuracy = 0.01))

        pFits <- pFits +
          scale_y_continuous(labels = scales::number_format(accuracy = 0.01))

        pSeries <- pSeries + theme_minimal(base_size = 14) +
          theme(plot.background = element_rect(color = "grey70",size=0.5))
        pFits <- pFits + theme_minimal(base_size = 14) +
          theme(plot.background = element_rect(color = "grey70",size=0.5))

        pCombined <- grid.arrange(pSeries,pFits)
}

```




